import type { ReactElement } from 'react';
import { Navigate, matchPath } from 'react-router-dom';
import OverviewPage from '../pages/tenant/OverviewPage';
import ModelConfigPage from '../pages/tenant/ModelConfigPage';
import ClawListPage from '../pages/tenant/ClawListPage';
import TemplateCenterPage from '../pages/tenant/TemplateCenterPage';
import TemplateCreatePage from '../pages/tenant/TemplateCreatePage';
import BrandPage from '../pages/tenant/BrandPage';
import BrandEditorPage from '../pages/tenant/BrandEditorPage';
import LaunchSpacePage from '../pages/tenant/LaunchSpacePage';
import WorkbenchPage from '../pages/tenant/WorkbenchPage';
import SkillsCenterPage from '../pages/tenant/SkillsCenterPage';
import AppsCenterPage from '../pages/tenant/AppsCenterPage';
import AppRegistrationPage from '../pages/tenant/AppRegistrationPage';
import ApiKeyManagementPage from '../pages/tenant/ApiKeyManagementPage';
import KnowledgeCenterPage from '../pages/tenant/KnowledgeCenterPage';
import KnowledgeConnectPage from '../pages/tenant/KnowledgeConnectPage';
import UserManagementPage from '../pages/tenant/UserManagementPage';
import UserSyncResultsPage from '../pages/tenant/UserSyncResultsPage';
import SeatPage from '../pages/tenant/SeatPage';
import NetworkPage from '../pages/tenant/NetworkPage';
import BillingPage from '../pages/tenant/BillingPage';
import ContractPage from '../pages/tenant/ContractPage';
import VoucherManagementPage, { VoucherDetailPage } from '../pages/tenant/VoucherManagementPage';
import PurchasePage from '../pages/tenant/PurchasePage';
import PaymentPage from '../pages/tenant/PaymentPage';
import ConsultPage from '../pages/tenant/ConsultPage';
import NewsPage from '../pages/tenant/NewsPage';
import SecurityPage from '../pages/tenant/SecurityPage';
import {
  TenantAuditLogPage,
  TenantBatchOpsCreatePage,
  TenantBatchOpsPage,
  TenantObservabilityPage,
  TenantOpsRedirectPage,
} from '../pages/tenant/TenantOpsPages';
import {
  AdminBankTransferReviewPage,
  AdminAgentDetailPage,
  AdminAgentsPage,
  AgentBalancePage,
  AdminCommissionBatchesPage,
  AdminCommissionRulesPage,
  AdminCommissionTransactionsPage,
  AdminCouponDetailPage,
  AdminCouponsPage,
  AdminDashboardPage,
  AdminInvoicesPage,
  AdminLeadsPage,
  AdminOpeningTasksPage,
  AdminOrdersPage,
  AdminPlansPage,
  AdminSalesPage,
  AdminSalesDetailPage,
  AdminStaffPage,
  AgentWebsitePage,
  AdminTenantDetailPage,
  AdminTenantsPage,
} from '../pages/admin/AdminConsolePages';
import {
  OpsTicketDetailPage,
  OpsTicketsPage,
} from '../pages/ops/OpsPages';
import NotificationsPage from '../pages/notifications/NotificationsPage';
import {
  AgentCommissionPage,
  SalesCouponsPage,
  SalesCouponPaymentPage,
  SalesCommissionPage,
  SalesCustomerCreatePage,
  SalesCustomerDetailPage,
  SalesCustomersPage,
  SalesLeadsPage,
  SalesOpeningTasksPage,
  SalesProfilePage,
} from '../pages/sales/SalesCrmPages';

export type AppLayoutMode = 'workspace' | 'detail' | 'focus' | 'fullscreen';

export interface AppRouteDefinition {
  path: string;
  element: ReactElement;
  pageName: string;
  layoutMode: AppLayoutMode;
  showBreadcrumb?: boolean;
}

export const appRoutes: AppRouteDefinition[] = [
  {
    path: '/agent',
    element: <Navigate to="/agent/admin" replace />,
    pageName: '代理镜像站',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin',
    element: <AdminDashboardPage />,
    pageName: '超级管理员（代理）工作台',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/dashboard',
    element: <Navigate to="/agent/admin" replace />,
    pageName: '超级管理员（代理）工作台',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/tenants',
    element: <AdminTenantsPage />,
    pageName: '代理客户管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/tenants/:id',
    element: <AdminTenantDetailPage />,
    pageName: '代理客户详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/orders',
    element: <AdminOrdersPage />,
    pageName: '代理采购订单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/orders/invoices',
    element: <AdminInvoicesPage />,
    pageName: '代理发票管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/orders/bank-transfer-review',
    element: <AdminBankTransferReviewPage />,
    pageName: '代理对公审核',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/tickets',
    element: <Navigate to="/agent/admin/delivery-tickets" replace />,
    pageName: '代理工单管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/delivery-tickets',
    element: <OpsTicketsPage />,
    pageName: '代理交付工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/support-tickets',
    element: <OpsTicketsPage />,
    pageName: '代理支持工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/delivery-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '代理交付工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/support-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '代理支持工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/sales',
    element: <AdminSalesPage />,
    pageName: '代理销售管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/sales/:id',
    element: <AdminSalesDetailPage />,
    pageName: '代理销售详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/leads',
    element: <AdminLeadsPage />,
    pageName: '代理咨询留资',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/commission',
    element: <Navigate to="/agent/admin/commission/transactions" replace />,
    pageName: '提现流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/commission/rules',
    element: <AdminCommissionRulesPage />,
    pageName: '代理结算规则',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/commission/transactions',
    element: <AdminCommissionTransactionsPage />,
    pageName: '提现流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/balance',
    element: <AgentBalancePage />,
    pageName: '代理订单总览',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/plans',
    element: <AdminPlansPage />,
    pageName: '代理套餐与价格',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/website',
    element: <AgentWebsitePage />,
    pageName: '网站管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/coupons',
    element: <VoucherManagementPage />,
    pageName: '代金券与优惠券',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/coupons/:couponId',
    element: <VoucherDetailPage />,
    pageName: '代理券详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/staff',
    element: <AdminStaffPage />,
    pageName: '代理员工账号',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/admin/notifications',
    element: <NotificationsPage role="platformAdmin" />,
    pageName: '超级管理员（代理）通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales',
    element: <SalesProfilePage />,
    pageName: '销售工作台',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/profile',
    element: <Navigate to="/agent/sales" replace />,
    pageName: '销售个人中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/customers',
    element: <SalesCustomersPage />,
    pageName: '销售客户池',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/customers/new',
    element: <SalesCustomerCreatePage />,
    pageName: '销售新增客户',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/customers/:id',
    element: <SalesCustomerDetailPage />,
    pageName: '销售客户详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/coupons',
    element: <SalesCouponsPage />,
    pageName: '代理销售优惠券',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/coupons/use',
    element: <PurchasePage />,
    pageName: '代理销售优惠券 / 代客户使用',
    layoutMode: 'focus',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/coupons/payment',
    element: <PaymentPage />,
    pageName: '代理销售优惠券 / 代客户支付',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/opening-tasks',
    element: <SalesOpeningTasksPage />,
    pageName: '销售订单跟进',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/commission',
    element: <AgentCommissionPage />,
    pageName: '我的销售分佣',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/leads',
    element: <SalesLeadsPage />,
    pageName: '销售咨询工单池',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/sales/notifications',
    element: <NotificationsPage role="sales" />,
    pageName: '销售通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance',
    element: <AdminDashboardPage />,
    pageName: '代理财务工作台',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/dashboard',
    element: <Navigate to="/agent/finance" replace />,
    pageName: '代理财务工作台',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/tenants',
    element: <AdminTenantsPage />,
    pageName: '代理财务客户管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/tenants/:id',
    element: <AdminTenantDetailPage />,
    pageName: '代理财务客户详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/orders',
    element: <AdminOrdersPage />,
    pageName: '代理财务采购订单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/orders/invoices',
    element: <AdminInvoicesPage />,
    pageName: '代理财务发票管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/orders/bank-transfer-review',
    element: <AdminBankTransferReviewPage />,
    pageName: '代理财务对公审核',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/sales',
    element: <AdminSalesPage />,
    pageName: '代理财务销售账户',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/sales/:id',
    element: <AdminSalesDetailPage />,
    pageName: '代理财务销售详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/commission',
    element: <AgentCommissionPage />,
    pageName: '代理财务佣金管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/commission/rules',
    element: <AdminCommissionRulesPage />,
    pageName: '代理财务结算规则',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/commission/transactions',
    element: <AgentCommissionPage />,
    pageName: '代理财务提现流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/balance',
    element: <AgentBalancePage />,
    pageName: '采购与结算',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/plans',
    element: <AdminPlansPage />,
    pageName: '代理财务套餐与价格',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/agent/finance/notifications',
    element: <NotificationsPage role="finance" />,
    pageName: '代理财务通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/overview',
    element: <OverviewPage />,
    pageName: '空间概览',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/overview/update/model',
    element: <ModelConfigPage />,
    pageName: '模型配置',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/templates',
    element: <TemplateCenterPage />,
    pageName: 'Claw 模板中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/templates/create',
    element: <TemplateCreatePage />,
    pageName: 'Claw 模板中心 / 创建模板',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/claws',
    element: <ClawListPage />,
    pageName: 'Claw 列表',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/purchase',
    element: <PurchasePage />,
    pageName: '购买席位',
    layoutMode: 'focus',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/payment',
    element: <PaymentPage />,
    pageName: '支付订单',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/skills',
    element: <SkillsCenterPage />,
    pageName: '技能中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/apps',
    element: <AppsCenterPage />,
    pageName: '应用中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/apps/create-agent',
    element: <AppRegistrationPage />,
    pageName: '应用中心 / 注册企业 Agent',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/apps/create-mcp',
    element: <AppRegistrationPage />,
    pageName: '应用中心 / 注册企业 MCP',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/knowledge',
    element: <KnowledgeCenterPage />,
    pageName: '知识中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/knowledge/connect',
    element: <KnowledgeConnectPage />,
    pageName: '知识中心 / 连接企业数据',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/users',
    element: <UserManagementPage />,
    pageName: '用户管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/users/sync-results',
    element: <UserSyncResultsPage />,
    pageName: '用户管理 / 更新员工数据',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/seats',
    element: <SeatPage />,
    pageName: '席位管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/network',
    element: <NetworkPage />,
    pageName: '网络配置',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/launch-space/create',
    element: <LaunchSpacePage />,
    pageName: '首次开通',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/brand',
    element: <BrandPage />,
    pageName: '品牌定制',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/brand/create',
    element: <BrandEditorPage />,
    pageName: '品牌定制 / 定制品牌信息',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/brand/:brandId/edit',
    element: <BrandEditorPage />,
    pageName: '品牌定制 / 定制品牌信息',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/workbench',
    element: <WorkbenchPage />,
    pageName: '员工端工作台配置',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/billing',
    element: <BillingPage />,
    pageName: '购买与账单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/vouchers',
    element: <Navigate to="/tenant/billing" replace />,
    pageName: '代金券与优惠券',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/vouchers/:voucherId',
    element: <Navigate to="/tenant/billing" replace />,
    pageName: '券详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/contracts',
    element: <ContractPage />,
    pageName: '合同管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/api-keys',
    element: <ApiKeyManagementPage />,
    pageName: 'API 密钥',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/consult',
    element: <ConsultPage />,
    pageName: '工单与咨询',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/news',
    element: <NewsPage />,
    pageName: '媒体资讯',
    layoutMode: 'workspace',
    showBreadcrumb: true,
  },
  {
    path: '/tenant/ops',
    element: <TenantOpsRedirectPage />,
    pageName: '运维管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/batch-ops',
    element: <TenantBatchOpsPage />,
    pageName: '运维管理 / 批量运维',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/batch-ops/create',
    element: <TenantBatchOpsCreatePage />,
    pageName: '运维管理 / 创建作业',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/observability',
    element: <TenantObservabilityPage />,
    pageName: '用量中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/audit',
    element: <TenantAuditLogPage />,
    pageName: '运维管理 / 审计日志',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/security',
    element: <SecurityPage />,
    pageName: '安全管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/tenant/notifications',
    element: <NotificationsPage role="tenantAdmin" />,
    pageName: '通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/dashboard',
    element: <AdminDashboardPage />,
    pageName: '全局仪表盘',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/tenants',
    element: <AdminTenantsPage />,
    pageName: '企业管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/tenants/:id',
    element: <AdminTenantDetailPage />,
    pageName: '企业详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/tenants/:id/impersonate',
    element: <Navigate to="/admin/tenants" replace />,
    pageName: '代登录企业空间',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/orders',
    element: <AdminOrdersPage />,
    pageName: '订单总览',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/orders/invoices',
    element: <AdminInvoicesPage />,
    pageName: '发票管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/orders/bank-transfer-review',
    element: <AdminBankTransferReviewPage />,
    pageName: '对公审核',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/orders/opening-tasks',
    element: <Navigate to="/admin/delivery-tickets" replace />,
    pageName: '开通工单分配',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/tickets',
    element: <Navigate to="/admin/delivery-tickets" replace />,
    pageName: '工单管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/delivery-tickets',
    element: <OpsTicketsPage />,
    pageName: '交付工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/support-tickets',
    element: <OpsTicketsPage />,
    pageName: '支持工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/delivery-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '交付工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/support-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '支持工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/sales',
    element: <AdminSalesPage />,
    pageName: '内部销售管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/sales/leaderboard',
    element: <Navigate to="/admin/sales" replace />,
    pageName: '销售排行榜',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/sales/transfers',
    element: <Navigate to="/admin/sales" replace />,
    pageName: '客户调拨审批',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/sales/:id',
    element: <AdminSalesDetailPage />,
    pageName: '销售详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/agents',
    element: <AdminAgentsPage />,
    pageName: '外部代理管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/agents/:id',
    element: <AdminAgentDetailPage />,
    pageName: '代理详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/commission/rules',
    element: <AdminCommissionRulesPage />,
    pageName: '结算规则',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/commission/transactions',
    element: <AdminCommissionTransactionsPage />,
    pageName: '佣金流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/commission/batches',
    element: <Navigate to="/admin/commission/transactions" replace />,
    pageName: '佣金结算单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/commissions',
    element: <Navigate to="/admin/commission/transactions" replace />,
    pageName: '佣金流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/plans',
    element: <AdminPlansPage />,
    pageName: '套餐与价格',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/coupons',
    element: <AdminCouponsPage />,
    pageName: '代金券与优惠券',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/coupons/:couponId',
    element: <AdminCouponDetailPage />,
    pageName: '券详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/pricing',
    element: <Navigate to="/admin/plans" replace />,
    pageName: '套餐与价格',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/news',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '资讯管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/news/create',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '新建资讯',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/news/:id/edit',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '编辑资讯',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/admin/leads',
    element: <AdminLeadsPage />,
    pageName: '咨询留资管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/system/roles',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '角色权限矩阵',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/system/dictionaries',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '字典管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/notifications',
    element: <NotificationsPage role="platformAdmin" />,
    pageName: '通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/system/params',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '系统参数',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/system/audit',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '全局审计日志',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/settings',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '角色权限矩阵',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/staff',
    element: <AdminStaffPage />,
    pageName: '内部员工',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/monitoring',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '系统监控与告警',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/admin/monitoring/alerts',
    element: <Navigate to="/admin/dashboard" replace />,
    pageName: '告警规则',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/dashboard',
    element: <AdminDashboardPage />,
    pageName: '财务仪表盘',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/tenants',
    element: <AdminTenantsPage />,
    pageName: '企业管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/tenants/:id',
    element: <AdminTenantDetailPage />,
    pageName: '企业详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/finance/tenants/:id/impersonate',
    element: <Navigate to="/finance/tenants" replace />,
    pageName: '代登录企业空间',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/finance/orders',
    element: <AdminOrdersPage />,
    pageName: '订单与账单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/orders/invoices',
    element: <AdminInvoicesPage />,
    pageName: '发票管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/orders/bank-transfer-review',
    element: <AdminBankTransferReviewPage />,
    pageName: '公账汇款审核',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/orders/opening-tasks',
    element: <Navigate to="/finance/orders" replace />,
    pageName: '开通工单进度',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/sales',
    element: <AdminSalesPage />,
    pageName: '销售账户',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/sales/leaderboard',
    element: <Navigate to="/finance/sales" replace />,
    pageName: '销售排行榜',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/sales/transfers',
    element: <Navigate to="/finance/sales" replace />,
    pageName: '客户调拨审批',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/sales/:id',
    element: <AdminSalesDetailPage />,
    pageName: '销售详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/finance/commission/rules',
    element: <AdminCommissionRulesPage />,
    pageName: '结算规则',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/commission/dashboard',
    element: <Navigate to="/finance/commission/transactions" replace />,
    pageName: '佣金流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/commission/transactions',
    element: <AdminCommissionTransactionsPage />,
    pageName: '提现流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/commission/review',
    element: <Navigate to="/finance/commission/transactions" replace />,
    pageName: '提现流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/commission/batches',
    element: <Navigate to="/finance/commission/transactions" replace />,
    pageName: '佣金结算单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/commissions',
    element: <Navigate to="/finance/commission/transactions" replace />,
    pageName: '佣金流水',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/plans',
    element: <AdminPlansPage />,
    pageName: '套餐与价格',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/pricing',
    element: <Navigate to="/finance/plans" replace />,
    pageName: '套餐与价格',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/finance/notifications',
    element: <NotificationsPage role="finance" />,
    pageName: '通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/tickets',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: '我的工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/delivery-tickets',
    element: <OpsTicketsPage />,
    pageName: '交付工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/support-tickets',
    element: <OpsTicketsPage />,
    pageName: '支持工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/delivery-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '交付工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/support-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '支持工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/notifications',
    element: <NotificationsPage role="deliveryOps" />,
    pageName: '通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/tenants',
    element: <AdminTenantsPage />,
    pageName: '企业管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/tenants/:id',
    element: <AdminTenantDetailPage />,
    pageName: '企业详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/orders',
    element: <AdminOrdersPage />,
    pageName: '订单与账单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/orders/bank-transfer-review',
    element: <AdminBankTransferReviewPage />,
    pageName: '公账汇款审核',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/orders/opening-tasks',
    element: <AdminOpeningTasksPage />,
    pageName: '开通工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/tickets',
    element: <Navigate to="/ops-admin/delivery-tickets" replace />,
    pageName: '工单管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/delivery-tickets',
    element: <OpsTicketsPage />,
    pageName: '交付工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/support-tickets',
    element: <OpsTicketsPage />,
    pageName: '支持工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/delivery-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '交付工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/support-tickets/:id',
    element: <OpsTicketDetailPage />,
    pageName: '支持工单详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/notifications',
    element: <NotificationsPage role="deliveryAdmin" />,
    pageName: '通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/tenants',
    element: <AdminTenantsPage />,
    pageName: '企业管理',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/tenants/:id',
    element: <AdminTenantDetailPage />,
    pageName: '企业详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/orders',
    element: <AdminOrdersPage />,
    pageName: '订单与账单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/orders/bank-transfer-review',
    element: <AdminBankTransferReviewPage />,
    pageName: '公账汇款审核',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops-admin/orders/opening-tasks',
    element: <Navigate to="/ops-admin/delivery-tickets?type=opening&view=all" replace />,
    pageName: '开通工单',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/im-binding',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: 'IM 绑定',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/im-binding/:tenantId',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: 'IM 绑定详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/bindings',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: 'IM 绑定',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/network',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: '网络配置',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/network/:tenantId',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: '网络配置详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/diagnosis',
    element: <Navigate to="/ops/support-tickets" replace />,
    pageName: '客户诊断与支持',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/diagnosis/:tenantId',
    element: <Navigate to="/ops/support-tickets" replace />,
    pageName: '客户诊断详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/support',
    element: <Navigate to="/ops/support-tickets" replace />,
    pageName: '客户诊断与支持',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/inspection',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: '健康巡检',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/inspection/rules',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: '巡检规则',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/ops/inspection/:runId',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: '巡检执行明细',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/ops/customers/:tenantId',
    element: <Navigate to="/ops/delivery-tickets" replace />,
    pageName: '客户运维档案',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin',
    element: <Navigate to="/sales-admin/coupons" replace />,
    pageName: '销售管理工作台',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/coupons',
    element: <SalesCouponsPage mode="salesAdmin" />,
    pageName: '销售优惠券分配',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/coupons/use',
    element: <PurchasePage />,
    pageName: '销售优惠券 / 代客户使用',
    layoutMode: 'focus',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/coupons/payment',
    element: <PaymentPage />,
    pageName: '销售优惠券 / 代客户支付',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/profile',
    element: <SalesProfilePage />,
    pageName: '销售个人中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/customers',
    element: <SalesCustomersPage />,
    pageName: '我的客户池',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/customers/new',
    element: <SalesCustomerCreatePage />,
    pageName: '我的客户池 / 新增客户',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/customers/:id',
    element: <SalesCustomerDetailPage />,
    pageName: '我的客户池 / 客户详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/opening-tasks',
    element: <SalesOpeningTasksPage />,
    pageName: '订单跟进',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/commission',
    element: <SalesCommissionPage />,
    pageName: '佣金明细',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/leads',
    element: <SalesLeadsPage />,
    pageName: '咨询工单池',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales-admin/notifications',
    element: <NotificationsPage role="salesAdmin" />,
    pageName: '通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/dashboard',
    element: <Navigate to="/sales/profile" replace />,
    pageName: '销售个人中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/customers',
    element: <SalesCustomersPage />,
    pageName: '我的客户池',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/customers/new',
    element: <SalesCustomerCreatePage />,
    pageName: '我的客户池 / 新增客户',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/sales/customers/:id',
    element: <SalesCustomerDetailPage />,
    pageName: '我的客户池 / 客户详情',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/sales/coupons',
    element: <SalesCouponsPage />,
    pageName: '销售优惠券',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/coupons/use',
    element: <PurchasePage />,
    pageName: '销售优惠券 / 代客户使用',
    layoutMode: 'focus',
    showBreadcrumb: false,
  },
  {
    path: '/sales/coupons/payment',
    element: <PaymentPage />,
    pageName: '销售优惠券 / 代客户支付',
    layoutMode: 'detail',
    showBreadcrumb: false,
  },
  {
    path: '/sales/share',
    element: <Navigate to="/sales/profile" replace />,
    pageName: '销售个人中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/opening-tasks',
    element: <SalesOpeningTasksPage />,
    pageName: '订单跟进',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/activation-codes',
    element: <Navigate to="/sales/opening-tasks" replace />,
    pageName: '订单跟进',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/invites',
    element: <Navigate to="/sales/profile" replace />,
    pageName: '销售个人中心',
    layoutMode: 'workspace',
    showBreadcrumb: true,
  },
  {
    path: '/sales/commission',
    element: <SalesCommissionPage />,
    pageName: '佣金明细',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/commissions',
    element: <Navigate to="/sales/commission" replace />,
    pageName: '佣金明细',
    layoutMode: 'workspace',
    showBreadcrumb: true,
  },
  {
    path: '/sales/leads',
    element: <SalesLeadsPage />,
    pageName: '咨询工单池',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/profile',
    element: <SalesProfilePage />,
    pageName: '销售个人中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
  {
    path: '/sales/notifications',
    element: <NotificationsPage role="sales" />,
    pageName: '通知中心',
    layoutMode: 'workspace',
    showBreadcrumb: false,
  },
];

export function getAppRouteMeta(pathname: string) {
  return appRoutes.find((route) => matchPath({ path: route.path, end: true }, pathname));
}
